"""Constantes del flujo conversacional y resultados de crédito."""

# Estados v2
START = "START"
MENU = "MENU"
CONSENTIMIENTO = "CONSENTIMIENTO"
ASK_CEDULA = "ASK_CEDULA"
NOT_ELIGIBLE = "NOT_ELIGIBLE"
ASK_INCOME = "ASK_INCOME"
ASK_EMPLOYMENT = "ASK_EMPLOYMENT"
ASK_EXPENSES = "ASK_EXPENSES"
ASK_TERM = "ASK_TERM"
ASK_PURPOSE = "ASK_PURPOSE"
SHOW_RESULT = "SHOW_RESULT"
CONFIRM = "CONFIRM"
HANDOFF_REQUESTED = "HANDOFF_REQUESTED"
FINISHED = "FINISHED"

# Resultados posibles de la evaluación crediticia
CREDIT_RESULT_PREAPPROVED = "preaprobado"
CREDIT_RESULT_OBSERVED = "observado"
CREDIT_RESULT_NOT_QUALIFIED = "no_cumple"

# Límites de validación
MAX_VALIDATION_FAILURES = 3
